services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb:/data
    restart: unless-stopped
  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    entrypoint: >
      /bin/sh -c "
        ollama serve &
        sleep 5 &&
        ollama pull mxbai-embed-large &&
        wait
      "
    restart: unless-stopped
